"""Add is_active column to Campaign model

Revision ID: b07e08e127ae
Revises: 16babb5e8503
Create Date: 2025-02-10 13:16:56.998732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07e08e127ae'
down_revision = '16babb5e8503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('views')
        batch_op.drop_column('withdrawn_amount')
        batch_op.drop_column('current_amount')

    with op.batch_alter_table('campaign_view', schema=None) as batch_op:
        batch_op.drop_constraint('unique_campaign_view', type_='unique')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('net_amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.alter_column('withdrawal_fee',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.alter_column('withdrawal_fee',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('net_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('campaign_view', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_campaign_view', ['campaign_id', 'ip_address'])

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('withdrawn_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.INTEGER(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('goal',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
